development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: flashes_development
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: flashes_testing
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: flashes_produciton
  pool: 5
  username: root
  password: 
